package connectFour.service;

public class LoginException extends RuntimeException{
    public LoginException(Throwable cause) {
        super(cause);
    }
}